# ═══════════════════════════════════════════════════════════════
#  Co-Simulation Engine — Application Configuration
# ═══════════════════════════════════════════════════════════════

spring.application.name=orchestrator-service
server.port=8087

# --- Kafka ---
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=cosimulation-engine
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# --- Kafka Topics ---
kafka.topic.gama-state=gama-state
kafka.topic.carla-state=carla-state
kafka.topic.carla-commands=carla-commands
kafka.topic.gama-commands=gama-commands

# --- Co-Simulation Rule Thresholds ---

# Pedestrian density (legacy road-based — disabled, kept for reference)
cosim.rules.pedestrian-density.high-threshold=2
cosim.rules.pedestrian-density.high-speed-limit=20
cosim.rules.pedestrian-density.medium-threshold=1
cosim.rules.pedestrian-density.medium-speed-limit=30

# Pedestrian density (geo-proximity — active)
# On met 2000m pour voir le résultat tout de suite (car ils sont à 1.1km)
cosim.rules.geo-proximity.radius-meters=50
# On diminue le nombre de piétons nécessaires à 1 seul pour déclencher le freinage
cosim.rules.geo-proximity.high-threshold=2
cosim.rules.geo-proximity.high-speed-limit=1
cosim.rules.geo-proximity.medium-threshold=1
cosim.rules.geo-proximity.medium-speed-limit=3
cosim.rules.geo-proximity.normal-speed-limit=8

cosim.rules.congestion.threshold=0.8

cosim.rules.pollution.threshold=0.9

# --- Actuator ---
management.endpoints.web.exposure.include=health,info,metrics
