spring.application.name=gama-adapter

server.port=8082

# GAMA WebSocket Configuration
gama.server.url=ws://localhost:6868
# Bruno's MobilitySimulator model
gama.model.path=${GAMA_MODEL_PATH:/home/chaymae/gama-simulation05052025/gama-simulation/models/mobilitySimulator/Launcher.gaml}
gama.experiment.name=Launch

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.client-id=gama-producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=gama-adapter-commands
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Kafka Topics
kafka.topic.gama-state=gama-state
kafka.topic.gama-commands=gama-commands
