spring.application.name=gama-adapter

server.port=8081

# GAMA WebSocket Configuration
gama.server.url=ws://localhost:6868
gama.model.path=/home/chaymae/Gama_Workspace/simple_test/models/Traffic and Pollution.gaml
gama.experiment.name=traffic

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.client-id=gama-producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Kafka Topics
kafka.topic.gama-state=gama-state
