apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /tmp/kompose_bin convert -f docker-compose.yml --out k8s/kompose-output/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: gama-adapter
  name: gama-adapter
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    io.kompose.service: gama-adapter
