apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /tmp/kompose_bin convert -f docker-compose.yml --out k8s/kompose-output/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: kafka-ui
  name: kafka-ui
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 8080
  selector:
    io.kompose.service: kafka-ui
