apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /tmp/kompose_bin convert -f docker-compose.yml --out k8s/kompose-output/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: orchestrator-service
  name: orchestrator-service
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8080
  selector:
    io.kompose.service: orchestrator-service
